services:
  openpose:
    build:
      context: ./openpose
    image: openpose:latest
    container_name: openpose
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - data:/data
    networks:
      - default
    tty: true
  smplify-x:
    build:
      context: ./smplify-x
    image: smplify-x:latest
    container_name: smplify-x
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - data:/data
    networks:
      - default
    tty: true
  blender:
    build:
      context: ./blender
    image: blender:latest
    container_name: blender
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - data:/data
    networks:
      - default
    tty: true
  backend:
    build:
      context: ./backend
    image: backend:latest
    container_name: backend
    volumes:
      - data:/data
    networks:
      - default
    tty: true

volumes:
  data:
    driver: local

networks:
  default:
    driver: bridge